default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_filepath: "./fastlane/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_ID']}.p8",
    )
    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/simsplit.ipa",
      app_identifier: "com.mazino2d.simsplit",
      skip_waiting_for_build_processing: true,
    )
  end

  desc "Submit a new build to App Store Connect for review"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_filepath: "./fastlane/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_ID']}.p8",
    )
    deliver(
      api_key: api_key,
      ipa: "../build/ios/ipa/simsplit.ipa",
      app_identifier: "com.mazino2d.simsplit",
      submit_for_review: false,  # Submit manually after review of metadata
      automatic_release: false,
      metadata_path: "./metadata",
    )
  end
end
